data:
  audio_dir: data/amicorpus
  annotation_dir: data/ami_public_manual_1.6.2
  recording_ids:
    - ES2002b
    - ES2002c
    - ES2002d
    - ES2003b
    - ES2004b
    - ES2005a
    - ES2005b

model:
  model_type: advanced
  window_sec: 3.0
  hop_sec: 1.5
  smoothing_kernel: 1

cluster:
  method: spectral
  estimate_num_speakers: true
  num_speakers: null
  max_speakers: 10
  n_neighbors: 10

segmentation:
  merge_gap: 0.25
  min_seg_dur: 0.75
  second_pass: true
  second_pass_min_dur: 2.0

speech:
  source: oracle   # change to "speechbrain_vad" for realistic setup
  min_speech_overlap: 0.5

vad:
  threshold: 0.00008   # only used if VAD enabled

evaluation:
  collar: 0.25
  ignore_overlap: true

runtime:
  debug: true
  cache_dir: outputs/cache
  use_cache: false